// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    aoz_sc_land_chest_opening
    (
        openChests
        getEnabled
        getChestTokenId
        enableSc
        disableSc
        setGuaranteedItem
        addGuaranteedSetItem
        addChanceSetItem
        clearGuaranteedItem
        clearGuaranteedItemSet
        clearChanceItemSet
        deposit
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
